name: Deploy docker image

on:
  push:
    branches:
      - deploy
      - main
  pull_request:
    branches:
      - deploy
      - main

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/info-broadcaster/frontend:${{ github.sha }} .
          docker push ghcr.io/info-broadcaster/frontend:${{ github.sha }}